### ISSUE TITLE
Character improvements

### ISSUE THREAD

**Issue by VexGodglove** [ryansigg/roll20-character-sheets#1]
Apocalypse World
In the character improvement section, each class has unique improvement options for that class. On your sheet these are not there, nor is there a place to add them in manually. This would be a useful addition.

**Comment by ryansigg** [comment]
@VexGodglove - Will add. 
Still working out how to make the Improvements area better/more legible. There's so much text... Update coming soon, sorry so late (having a kid takes one out of the game, pun intended) for a bit...

**Comment by ryansigg** [comment]
Added a basic Repeating improvements area. Will add more with next big update.
