### ISSUE TITLE
No Brainer character sheet?

### ISSUE THREAD

**Issue by borogove** [ryansigg/roll20-character-sheets#2]
I don't see an option to select Brainer among the character classes! This saddens me.

**Comment by ryansigg** [comment]
Hey @borogove I missed this, apologies!

Will be adding Brainer as well as the extra classes in the next update.

**Comment by ryansigg** [comment]
well, not ALL the extra (limited) playbooks... I suspect that some of the weirder ones will be harder to integrate into the system.
